---
  - name: Python3 | Check is installed
    shell: "python3 --version"
    register: py3_installed
    ignore_errors: true
    failed_when: "'Python {{python_version}}' not in py3_installed.stdout"
    tags:
      - python3

  - name: Python3 | install dependencies
    apt: pkg="{{item}}" state="present"
    register: py3_installed | failed
    with_items:
      - "make"
    tags:
      - python3

  - name: Python3 | Download distribution
    get_url:
      url: "https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz"
      dest: /tmp/Python-{{python_version}}.tgz
    when: py3_installed | failed
    tags:
      - python3

  - name: Python3 | Unpack distribution
    unarchive:
      src: /tmp/Python-{{python_version}}.tgz
      dest: /tmp
      remote_src: yes
    when: py3_installed | failed
    tags:
      - python3

  - name: Python3 | Configure for install
    shell: "./configure"
    args:
      chdir: "/tmp/Python-{{python_version}}"
    when: py3_installed | failed
    tags:
      - python3

  - name: Python3 | make
    shell: "make"
    args:
      chdir: "/tmp/Python-{{python_version}}"
    when: py3_installed | failed
    become: yes
    tags:
      - python3

  - name: Python3 | make install
    shell: "make install"
    args:
      chdir: "/tmp/Python-{{python_version}}"
    when: py3_installed | failed
    become: yes
    tags:
      - python3
