---
- name: Prepare
  hosts: all
  tasks:

    - debug: msg="ansible_os_family={{ ansible_os_family }}"

    - name: Install development tools packages
      yum:
        name:
          - "@development-tools"
        state=present
        update_cache=yes
      when: ansible_os_family in ["Redhat", "CentOS"]

    - name: Install development tools packages
      apt:
        name:
          - "build-essential"
        state=present
        update_cache=yes
      when: ansible_os_family in ["Debian"]
